import feedparser
import requests
import os
import datetime
import json
from urllib.parse import urljoin
from bs4 import BeautifulSoup

# --- Configuration ---
SEBI_NOTIFICATIONS_FEED = 'https://www.sebi.gov.in/rss/rss.xml'

# Dictionary of URLs for INDEX PAGES to scrape (Circulars, Regulations, etc.)
# These pages use tables listing documents. The 'search=...' parameter often gives the list.
SEBI_INDEX_URLS = {
    # CRITICAL: Official Instructions & Guidelines
    'Circulars': 'https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListingAll=yes&search=Circular',
    # CRITICAL: Consolidated Rules (like RBI's Master Directions)
    'Master_Circulars': 'https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListingAll=yes&search=Master%20Circulars',
    # Foundational legal documents
    'Regulations': 'https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListingLegal=yes&sid=1&ssid=3&smid=0',
    # Major announcements
    'Press_Releases': 'https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListingAll=yes&search=Press%20Release',
}

DOWNLOAD_DIR = 'sebi_knowledge_base'
STATUS_FILE = 'sebi_download_audit_status.json'

# Global tracker for status and duplicate checks
download_status_tracker = {}

# --- Utility Functions (Same as previous script) ---

def load_status(file_path):
    # ... (omitted for brevity)
    if os.path.exists(file_path):
        try:
            with open(file_path, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError:
            print(f"[WARNING] Could not decode {file_path}. Starting fresh tracker.")
            return {}
    return {}

def save_status(data, file_path):
    # ... (omitted for brevity)
    with open(file_path, 'w') as f:
        json.dump(data, f, indent=4)
    print(f"\n--- Data saved to {file_path} ---")

def setup_directory():
    # ... (omitted for brevity)
    if not os.path.exists(DOWNLOAD_DIR):
        os.makedirs(DOWNLOAD_DIR)
        print(f"Created download directory: {DOWNLOAD_DIR}")

def sanitize_filename(title, source_key):
    # ... (omitted for brevity)
    date_str = datetime.datetime.now().strftime('%Y%m%d')
    safe_title = ''.join(c if c.isalnum() or c in (' ', '_', '-') else '' for c in title)
    safe_title = safe_title.strip().replace(' ', '_')
    filename = f"{source_key}_{date_str}_{safe_title}.pdf"
    return filename[:200]

def download_file(pdf_url, filename):
    # ... (omitted for brevity)
    try:
        full_path = os.path.join(DOWNLOAD_DIR, filename)
        if os.path.exists(full_path):
            print(f"   [SKIP] File already exists: {filename}")
            return True
        response = requests.get(pdf_url, stream=True, timeout=30)
        response.raise_for_status()
        with open(full_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192): 
                f.write(chunk)
        print(f"   [SUCCESS] Downloaded: {filename}")
        return True
    except requests.exceptions.RequestException as e:
        print(f"   [ERROR] Failed to download {pdf_url}: {e}")
        return False
# --- SEBI Specific Logic (Modified) ---

def find_pdf_link(html_url):
    """
    Visits the SEBI document page and reliably searches for the direct PDF download link,
    prioritizing links related to the consistent download structure (like the <button id=download>
    or adjacent PDF links).
    """
    try:
        response = requests.get(html_url, timeout=15)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # 1. Look for the <button id="download"> element
        download_button = soup.find('button', id='download')
        
        if download_button:
            # The PDF link might be stored in a data attribute (e.g., data-pdf-url) 
            # or generated by JavaScript. The safest scrape is to look for the final PDF link 
            # *near* the button.

            # Look for the last anchor tag (<a>) on the page that links to a PDF, 
            # as this is often the final resolved URL in the viewer.
            
            # Find all potential PDF links
            pdf_links = [a for a in soup.find_all('a', href=True) if a['href'].lower().endswith('.pdf')]
            
            if pdf_links:
                # Often the last PDF link found is the largest/correct one to download
                final_pdf_link = pdf_links[-1]['href']
                print(f"   -> Found PDF link via download button proximity/consistency.")
                return urljoin(html_url, final_pdf_link)

        # 2. Fallback to generic PDF link search if the button/proximity check fails
        for link_element in soup.find_all('a', href=True):
            href = link_element['href']
            
            # Pattern 1: Links ending with .pdf (Direct link)
            if href.lower().endswith('.pdf'):
                return urljoin(html_url, href)
                
            # Pattern 2: Links containing specific document identifiers in the path
            if ('/legal/circulars/' in href.lower() or '/pr/' in href.lower()) and any(ext in href.lower() for ext in ['.pdf', '.doc', '.docx']):
                return urljoin(html_url, href)

    except requests.exceptions.RequestException as e:
        print(f"   [ERROR] Failed to fetch HTML page {html_url}: {e}")
        
    return None

# ... (rest of the script remains the same) ...
def process_sebi_rss_feed():
    """Monitors the SEBI RSS feed and queues items for download."""
    # ... (Logic remains the same as in the previous script)
    print("\n--- Processing SEBI Real-Time RSS Feed ---")
    rss_links = []
    try:
        feed = feedparser.parse(SEBI_NOTIFICATIONS_FEED)
        for entry in feed.entries:
            title = entry.get('title', 'No Title')
            link = entry.get('link', None)
            category = entry.get('sebi_category', entry.get('tags', [{}])[0].get('term', 'Document'))
            source_key = category.replace(' ', '_').strip()
            
            if link:
                rss_links.append({
                    'title': title, 
                    'link': link, 
                    'source_key': f"RSS_{source_key}" # Prefix with RSS for clarity
                })
    except Exception as e:
        print(f"--- [CRITICAL ERROR] Could not parse SEBI RSS feed: {e}")
    return rss_links

def scrape_sebi_index_page(source_key, index_url):
    """
    Scrapes a SEBI index page which uses a consistent table format.
    The SEBI tables typically have columns: Date, Type, Title/Link.
    """
    print(f"\n--- Scraping Index: {source_key} ({index_url}) ---")
    document_links = []
    
    try:
        response = requests.get(index_url, timeout=20)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # SEBI often uses simple tables within the main content area
        main_table = soup.find('table') 
        if not main_table:
            print(f"[WARNING] Could not find the main data table on {source_key}.")
            return []

        # 1. Get headers (used for alignment verification)
        headers = [th.text.strip().replace('\n', ' ') for th in main_table.find('tr').find_all(['th', 'td'])]
        # Common SEBI columns: ['Date', 'Type', 'Title'] or ['Issued Year', 'Regulations']
        
        # 2. Iterate over data rows (skip header row)
        rows = main_table.find_all('tr')[1:] 
        
        for row in rows:
            cols = row.find_all('td')
            if len(cols) < 2: 
                continue # Skip empty or malformed rows

            # Attempt to extract Date (often Col 0), Type (Col 1), and Title/Link (Col 2 or 1)
            date_text = cols[0].text.strip() if len(cols) > 0 else "N/A"
            type_text = cols[1].text.strip() if len(cols) > 1 else source_key
            title = None
            link = None
            
            # Find the link element (a tag) within the available columns
            link_element = row.find('a', href=True)
            if link_element:
                link = urljoin(index_url, link_element['href'])
                title = link_element.text.strip()
            
            if title and link:
                document_links.append({
                    'title': title, 
                    'link': link, 
                    'source_key': f"{source_key}_{type_text.replace(' ', '_')}", # e.g., Circulars_Regulations
                    'metadata_date': date_text
                })
                    
        print(f"Found {len(document_links)} potential document links on {source_key} index.")
        
    except requests.exceptions.RequestException as e:
        print(f"   [CRITICAL ERROR] Failed to fetch index page {index_url}: {e}")
        
    return document_links


def process_all_links(all_document_links):
    """
    Iterates through all collected SEBI document links, checks the audit file, 
    and downloads only new or failed records.
    """
    global download_status_tracker
    unique_links = set()
    print(f"\n--- Starting Processing of {len(all_document_links)} Total Links ---")
    
    skipped_count = 0
    download_queue = []
    
    # Filter the list based on audit status
    for doc in all_document_links:
        link = doc['link']
        
        # Check 1: Audit status
        if link in download_status_tracker and download_status_tracker[link]['downloaded']:
            skipped_count += 1
            continue
            
        # Check 2: Deduplication within the current run
        if link in unique_links:
            continue
            
        unique_links.add(link)
        download_queue.append(doc)

    print(f"Skipped {skipped_count} documents already marked as successful.")
    print(f"Processing {len(download_queue)} new or failed documents.")

    # Process the download queue (download logic is the same)
    for doc in download_queue:
        link = doc['link']
        title = doc['title']
        source_key = doc['source_key']
        
        print(f"\n[PROCESSING] {source_key} - {title[:80]}...")
        
        pdf_url = None
        
        if link.lower().endswith('.pdf'):
            pdf_url = link
        else:
            pdf_url = find_pdf_link(link)
        
        success = False
        filename = None
        
        if pdf_url:
            filename = sanitize_filename(title, source_key)
            
            # Check if file exists on disk
            if os.path.exists(os.path.join(DOWNLOAD_DIR, filename)):
                print(f"   [SKIP] File already exists on disk: {filename}")
                success = True
            else:
                success = download_file(pdf_url, filename)
        else:
            print("   [FAILED] Could not find a downloadable PDF link.")
        
        # Update Status Tracker
        download_status_tracker[link] = {
            'title': title, 
            'source': source_key,
            'downloaded': success, 
            'filename': filename if success else None,
            'final_pdf_url': pdf_url,
            'source_html_link': link,
            'metadata_date': doc.get('metadata_date', 'N/A') # Add the date from the index
        }

def main():
    """Orchestrates the SEBI scraping process (RSS + Index)."""
    global download_status_tracker
    download_status_tracker = load_status(STATUS_FILE)
    setup_directory()
    
    all_document_links = []
    
    # STEP 1: Process the SEBI RSS Feed (Real-time updates)
    all_document_links.extend(process_sebi_rss_feed())
    
    # STEP 2: Scrape the SEBI Index pages (Historical/Comprehensive coverage)
    for source_key, url in SEBI_INDEX_URLS.items():
        links = scrape_sebi_index_page(source_key, url)
        all_document_links.extend(links)
        
    # STEP 3: Process and download all unique document links
    process_all_links(all_document_links)

    # STEP 4: Save the final audit status
    save_status(download_status_tracker, STATUS_FILE)
    
    # 5. Final summary
    downloaded_count = sum(1 for status in download_status_tracker.values() if status['downloaded'])
    failed_count = sum(1 for status in download_status_tracker.values() if not status['downloaded'])
    print(f"\n===========================================")
    print(f"| SEBI Ingestion Summary:")
    print(f"| Total Unique Documents Tracked: {len(download_status_tracker)}")
    print(f"| Successfully Downloaded: {downloaded_count}")
    print(f"| Failed Downloads: {failed_count}")
    print(f"| Audit Saved to: {STATUS_FILE}")
    print(f"===========================================")
    
if __name__ == '__main__':
    main()